package Entidades;
// Generated 28/05/2015 10:06:31 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bebida generated by hbm2java
 */
public class Bebida  implements java.io.Serializable {


     private int id;
     private String nombre;
     private int precioPe;
     private int cantidadb;
     private Set historials = new HashSet(0);

    public Bebida() {
    }

	
    public Bebida(int id, String nombre, int precioPe, int cantidadb) {
        this.id = id;
        this.nombre = nombre;
        this.precioPe = precioPe;
        this.cantidadb = cantidadb;
    }
    public Bebida(int id, String nombre, int precioPe, int cantidadb, Set historials) {
       this.id = id;
       this.nombre = nombre;
       this.precioPe = precioPe;
       this.cantidadb = cantidadb;
       this.historials = historials;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getPrecioPe() {
        return this.precioPe;
    }
    
    public void setPrecioPe(int precioPe) {
        this.precioPe = precioPe;
    }
    public int getCantidadb() {
        return this.cantidadb;
    }
    
    public void setCantidadb(int cantidadb) {
        this.cantidadb = cantidadb;
    }
    public Set getHistorials() {
        return this.historials;
    }
    
    public void setHistorials(Set historials) {
        this.historials = historials;
    }

    @Override
    public String toString() {
        return "Bebida{" + "id=" + id + ", nombre=" + nombre + ", precioPe=" + precioPe + ", cantidadb=" + cantidadb +'}';
    }




}


